# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_auto_20160806_1641'),
        ('users', '0002_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Lawyer',
            new_name='Specialist',
        ),
        migrations.RemoveField(
            model_name='student',
            name='baseuser',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
