# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyer'),
        ('disputes', '0002_auto_20160806_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('times_created', models.DateTimeField(auto_now_add=True)),
                ('customer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_customer1', to='users.Customer')),
                ('customer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_customer2', to='users.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
