# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160806_1641'),
        ('disputes', '0003_auto_20160806_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.Dispute')),
            ],
        ),
        migrations.AddField(
            model_name='disputedocument',
            name='dispute_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.DisputeMaterial'),
        ),
    ]
