# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0006_auto_20160806_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputematerial',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='disputes.Dispute'),
        ),
    ]
