# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0007_auto_20160807_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeCategoryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('dispute_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.DisputeCategory')),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='alt_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
