# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0008_auto_20160807_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='alt_id',
            field=models.IntegerField(unique=True),
        ),
    ]
