# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0009_auto_20160807_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputecategoryquestion',
            name='dispute_category',
        ),
        migrations.DeleteModel(
            name='DisputeCategory',
        ),
        migrations.DeleteModel(
            name='DisputeCategoryQuestion',
        ),
    ]
