# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0010_auto_20160807_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeQNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('dispute_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.DisputeMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='category',
            field=models.IntegerField(choices=[(1, 'Crime'), (2, 'Family')], default=1),
            preserve_default=False,
        ),
    ]
