# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 08:52
from __future__ import unicode_literals

import disputes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0011_auto_20160807_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='alt_id',
            field=models.IntegerField(default=disputes.models.make_alt_id, unique=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='category',
            field=models.IntegerField(choices=[(1, 'Crime (with demo questions)'), (2, 'Family (with demo questions)')]),
        ),
    ]
