# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20160806_1641'),
        ('disputes', '0004_auto_20160806_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.Dispute')),
                ('graduate_set', models.ManyToManyField(to='users.Graduate')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('resolution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resolutions.Resolution')),
            ],
        ),
    ]
