# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160806_1641'),
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionResolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resolutiondocuments',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='graduate_set',
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='specialist',
        ),
        migrations.AddField(
            model_name='resolution',
            name='graduate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Graduate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolution',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ResolutionDocuments',
        ),
        migrations.AddField(
            model_name='resolutionresolve',
            name='resolution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resolutions.Resolution'),
        ),
        migrations.AddField(
            model_name='resolutionresolve',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Specialist'),
        ),
        migrations.AddField(
            model_name='resolutionproposal',
            name='resolution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resolutions.Resolution'),
        ),
    ]
