# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_auto_20160806_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='valid',
        ),
        migrations.AddField(
            model_name='resolution',
            name='state',
            field=models.IntegerField(choices=[(0, 'invalid'), (1, 'assigned'), (2, 'proposed'), (3, 'approved')], default=1),
        ),
    ]
